import React, { useState, useMemo, useCallback, useRef, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
  StatusBar,
  Animated,
  Modal,
  Pressable,
  FlatList,
  ActivityIndicator,
  Image,
  Dimensions,
  Easing,
} from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useTranslation } from 'react-i18next';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import * as Contacts from 'expo-contacts';
import * as ImagePicker from 'expo-image-picker';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../lib/auth-context';
import { useAppTheme, ThemeColors } from '../../lib/theme-context';
import { useSubscription } from '../../lib/subscription-context';
import { RootStackParamList } from '../../navigation/AppNavigator';
import { CurrencyCode, ParsedReceipt, ParsedReceiptItem } from '../../types/database';
import { formatCurrency } from '../../utils/balance';
import {
  generateMultiDebtorNotification,
  shareViaWhatsApp,
} from '../../utils/whatsapp';
import { Spacing, Radius, FontFamily } from '../../theme';
import FunButton from '../../components/FunButton';
import ThemedCard from '../../components/ThemedCard';
import ThemedInput from '../../components/ThemedInput';
import BouncyPressable from '../../components/BouncyPressable';
import useScreenEntrance from '../../hooks/useScreenEntrance';
import { useAlert } from '../../hooks/useAlert';
import { useNearbyUsers } from '../../hooks/useNearbyUsers';
import { User } from '../../types/database';

type Props = NativeStackScreenProps<RootStackParamList, 'QuickSplit'>;

interface Person {
  id: string;
  name: string;
  phone: string | null;
}

interface PhoneContact {
  id: string;
  name: string;
  phone: string;
}

const CURRENCIES: CurrencyCode[] = [
  'EGP', 'USD', 'EUR', 'GBP', 'SAR', 'AED', 'KWD', 'INR', 'PKR', 'TRY', 'CAD', 'AUD', 'BRL',
];

const AVATAR_GRADIENTS: [string, string][] = [
  ['#0D9488', '#14B8A6'],
  ['#A67C00', '#D4AF37'],
  ['#7C3AED', '#A78BFA'],
  ['#DC2626', '#F87171'],
  ['#2563EB', '#60A5FA'],
  ['#D97706', '#FBBF24'],
  ['#059669', '#34D399'],
  ['#DB2777', '#F472B6'],
];

function avatarGradient(name: string): [string, string] {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = (hash * 31 + name.charCodeAt(i)) | 0;
  }
  return AVATAR_GRADIENTS[Math.abs(hash) % AVATAR_GRADIENTS.length];
}

function getInitials(name: string): string {
  const parts = name.trim().split(/\s+/);
  if (parts.length >= 2) return (parts[0][0] + parts[1][0]).toUpperCase();
  return name.slice(0, 2).toUpperCase();
}

// Generate a unique local ID for UI state management
// (UUIDs will be generated by Supabase during insertion)
function nextId(): string {
  return `p_${Math.random().toString(36).substring(2, 15)}_${Math.random().toString(36).substring(2, 15)}`;
}

export default function QuickSplitScreen({ navigation }: Props) {
  const { t, i18n } = useTranslation();
  const { user, profile } = useAuth();
  const { colors, isDark } = useAppTheme();
  const alert = useAlert();
  const insets = useSafeAreaInsets();
  const styles = useMemo(() => createStyles(colors, isDark), [colors, isDark]);
  const entrance = useScreenEntrance();

  // Form state
  const [description, setDescription] = useState('');
  const [amountStr, setAmountStr] = useState('');
  const [currency, setCurrency] = useState<CurrencyCode>(
    (profile?.preferred_currency as CurrencyCode) || 'EGP'
  );
  const [people, setPeople] = useState<Person[]>([]);
  const [saving, setSaving] = useState(false);

  // Add person modal
  const [addModalVisible, setAddModalVisible] = useState(false);
  const [manualName, setManualName] = useState('');
  const [manualPhone, setManualPhone] = useState('');

  // Contacts picker modal
  const [contactsModalVisible, setContactsModalVisible] = useState(false);
  const [contacts, setContacts] = useState<PhoneContact[]>([]);
  const [contactSearch, setContactSearch] = useState('');
  const [loadingContacts, setLoadingContacts] = useState(false);

  // BLE nearby discovery
  const [nearbyModalVisible, setNearbyModalVisible] = useState(false);
  const { nearbyUsers, isScanning, error: bleError, startScan, stopScan } = useNearbyUsers();

  // Receipt scanning
  type EntryMode = 'landing' | 'scanning' | 'form';
  const [entryMode, setEntryMode] = useState<EntryMode>('landing');
  const [scannedItems, setScannedItems] = useState<ParsedReceiptItem[]>([]);
  const [scanExtras, setScanExtras] = useState({ tax: 0, serviceCharge: 0 });
  const [scanPreviewUri, setScanPreviewUri] = useState<string | null>(null);
  const iconPulse = useRef(new Animated.Value(1)).current;
  const { canPerform, incrementUsage } = useSubscription();

  // Animate icon pulse when landing mode
  useEffect(() => {
    if (entryMode === 'landing') {
      Animated.loop(
        Animated.sequence([
          Animated.timing(iconPulse, {
            toValue: 1.08,
            duration: 1200,
            easing: Easing.inOut(Easing.ease),
            useNativeDriver: true,
          }),
          Animated.timing(iconPulse, {
            toValue: 1,
            duration: 1200,
            easing: Easing.inOut(Easing.ease),
            useNativeDriver: true,
          }),
        ])
      ).start();
    }
  }, [entryMode, iconPulse]);

  const totalAmount = parseFloat(amountStr) || 0;
  const splitCount = people.length + 1; // +1 for the payer
  const perPerson = splitCount > 1 ? Math.round((totalAmount / splitCount) * 100) / 100 : 0;
  const isValid = description.trim().length > 0 && totalAmount > 0 && people.length > 0;

  // --- Contact picker ---
  const openContactsPicker = useCallback(async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    setLoadingContacts(true);
    setContactsModalVisible(true);
    setContactSearch('');

    try {
      const { status } = await Contacts.requestPermissionsAsync();
      if (status !== 'granted') {
        alert.warning(
          t('addFriends.permissionNeeded'),
          t('addFriends.permissionExplain')
        );
        setContactsModalVisible(false);
        setLoadingContacts(false);
        return;
      }

      const { data } = await Contacts.getContactsAsync({
        fields: [Contacts.Fields.PhoneNumbers, Contacts.Fields.Name],
        sort: Contacts.SortTypes.FirstName,
      });

      const phoneContacts: PhoneContact[] = [];
      for (const c of data) {
        if (c.phoneNumbers && c.phoneNumbers.length > 0 && c.name) {
          const phone = c.phoneNumbers[0].number?.replace(/[\s\-()]/g, '') || '';
          if (phone) {
            phoneContacts.push({
              id: c.id || phone,
              name: c.name,
              phone,
            });
          }
        }
      }

      setContacts(phoneContacts);
    } catch {
      alert.error(t('common.error'));
      setContactsModalVisible(false);
    } finally {
      setLoadingContacts(false);
    }
  }, [alert, t]);

  const filteredContacts = useMemo(() => {
    if (!contactSearch.trim()) return contacts;
    const q = contactSearch.toLowerCase();
    return contacts.filter(
      (c) =>
        c.name.toLowerCase().includes(q) || c.phone.includes(q)
    );
  }, [contacts, contactSearch]);

  const addContactAsPerson = useCallback(
    (contact: PhoneContact) => {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      // Avoid duplicates
      if (people.some((p) => p.phone === contact.phone)) return;
      setPeople((prev) => [
        ...prev,
        { id: nextId(), name: contact.name, phone: contact.phone },
      ]);
      setContactsModalVisible(false);
    },
    [people]
  );

  // --- Manual add ---
  const addManualPerson = () => {
    const name = manualName.trim();
    if (!name) return;
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    const phone = manualPhone.trim() || null;
    setPeople((prev) => [...prev, { id: nextId(), name, phone }]);
    setManualName('');
    setManualPhone('');
    setAddModalVisible(false);
  };

  const removePerson = (id: string) => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    setPeople((prev) => prev.filter((p) => p.id !== id));
  };

  // --- BLE Nearby Discovery ---
  const openNearbyModal = useCallback(async () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    if (!user?.id) return;
    setNearbyModalVisible(true);
    await startScan(user.id);
  }, [user, startScan]);

  const addNearbyUserAsPerson = useCallback(
    (nearbyUser: User) => {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      if (people.some((p) => p.id === nearbyUser.id)) return;
      setPeople((prev) => [
        ...prev,
        {
          id: nearbyUser.id,
          name: nearbyUser.display_name,
          phone: nearbyUser.phone,
        },
      ]);
      stopScan();
      setNearbyModalVisible(false);
    },
    [people, stopScan]
  );

  const closeNearbyModal = useCallback(() => {
    stopScan();
    setNearbyModalVisible(false);
  }, [stopScan]);

  // --- Receipt Scanning ---
  const parseReceiptWithOpenAI = async (base64: string): Promise<ParsedReceipt> => {
    const apiKey = process.env.EXPO_PUBLIC_OPENAI_API_KEY;
    if (!apiKey) throw new Error(t('scanner.apiKeyMissing'));

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'gpt-4.1',
        messages: [
          {
            role: 'system',
            content: `You are an expert receipt OCR parser for Fifti, a bill-splitting app. You can read receipts in any language including Arabic, English, and others.
Your job is to extract EVERY line item from a receipt image with maximum accuracy.

CRITICAL RULES:
1. Read the receipt character by character. Do NOT guess or hallucinate items or prices.
2. Item names MUST be exactly as printed on the receipt (Arabic or English). Keep the original language.
3. quantity defaults to 1 if not explicitly shown. unit_price = total / quantity.
4. If an item shows "2x", "x2", "×2", "٢×", or a qty column, set quantity accordingly.
5. Currency is EGP unless you see "$", "USD", "€", or "EUR" printed on the receipt.
6. Tax lines: look for "ضريبة", "Tax", "VAT", "ض.ق.م", "ضريبه", "14%" → put in "tax" field.
7. Service charge lines: look for "خدمة", "Service", "Svc", "سرفيس", "سيرفيس", "12%" → put in "service_charge" field.
8. Discount lines: look for "خصم", "Discount", "Disc" → subtract from subtotal, do NOT include as item.
9. Do NOT include tax, service charge, subtotal, total, or discount as items — they go in their own fields.
10. "total" = subtotal + tax + service_charge - discount. Cross-check with the receipt total.
11. If the receipt has Arabic text, read right-to-left. Numbers are always left-to-right.
12. If prices use Arabic numerals (٠١٢٣٤٥٦٧٨٩), convert them to standard digits.
13. Watch out for dot vs comma as decimal separator. "12,50" means 12.50.
14. If receipt is blurry, extract only what you can read confidently. Never invent data.

JSON schema (return ONLY valid JSON, no markdown, no extra text):
{
  "items": [{"name": "string", "quantity": number, "unit_price": number, "total": number}],
  "subtotal": number,
  "tax": number,
  "service_charge": number,
  "total": number,
  "currency": "EGP" | "USD",
  "merchant_name": "string or null"
}`,
          },
          {
            role: 'user',
            content: [
              {
                type: 'image_url',
                image_url: {
                  url: `data:image/jpeg;base64,${base64}`,
                  detail: 'high',
                },
              },
              {
                type: 'text',
                text: 'Parse this receipt image. Read every line carefully and extract all food/drink items with exact names and prices as printed. Be extremely precise with numbers.',
              },
            ],
          },
        ],
        temperature: 0,
        max_tokens: 4096,
        response_format: { type: 'json_object' },
      }),
    });

    if (!response.ok) {
      const err = await response.json().catch(() => ({}));
      throw new Error(
        err.error?.message || `OpenAI API error (${response.status})`
      );
    }

    const data = await response.json();
    const parsed = JSON.parse(data.choices[0].message.content);

    if (!parsed.items) parsed.items = [];
    if (!parsed.tax) parsed.tax = 0;
    if (!parsed.service_charge) parsed.service_charge = 0;
    if (!parsed.currency) parsed.currency = 'EGP';
    parsed.subtotal = parsed.items.reduce(
      (s: number, i: any) => s + (i.total || i.unit_price * i.quantity),
      0
    );
    if (!parsed.total)
      parsed.total = parsed.subtotal + parsed.tax + parsed.service_charge;

    return parsed as ParsedReceipt;
  };

  function decode(base64: string): Uint8Array {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    const bufferLength = base64.length * 0.75;
    const bytes = new Uint8Array(bufferLength);
    let p = 0;
    for (let i = 0; i < base64.length; i += 4) {
      const a = chars.indexOf(base64[i]);
      const b = chars.indexOf(base64[i + 1]);
      const c = chars.indexOf(base64[i + 2]);
      const d = chars.indexOf(base64[i + 3]);
      bytes[p++] = (a << 2) | (b >> 4);
      bytes[p++] = ((b & 15) << 4) | (c >> 2);
      bytes[p++] = ((c & 3) << 6) | d;
    }
    return bytes;
  }

  const scanReceipt = useCallback(
    async (useCamera: boolean) => {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);

      const scanCheck = await canPerform('receipt_scan');
      if (!scanCheck.allowed) {
        navigation.navigate('Paywall', { trigger: 'receipt_scan_limit' });
        return;
      }

      const permResult = useCamera
        ? await ImagePicker.requestCameraPermissionsAsync()
        : await ImagePicker.requestMediaLibraryPermissionsAsync();

      if (!permResult.granted) {
        alert.warning(
          t('scanner.permissionRequired'),
          t('scanner.permissionMessage')
        );
        return;
      }

      const result = useCamera
        ? await ImagePicker.launchCameraAsync({
            mediaTypes: ['images'],
            quality: 0.8,
            base64: true,
          })
        : await ImagePicker.launchImageLibraryAsync({
            mediaTypes: ['images'],
            quality: 0.8,
            base64: true,
          });

      if (result.canceled || !result.assets[0]) return;

      const { base64: b64, uri } = result.assets[0];
      setScanPreviewUri(uri);
      setEntryMode('scanning');

      try {
        const fileName = `receipts/${Date.now()}.jpg`;
        supabase.storage
          .from('receipts')
          .upload(fileName, decode(b64!), { contentType: 'image/jpeg' });

        let receiptData: ParsedReceipt;
        try {
          const { data, error } = await supabase.functions.invoke(
            'scan-receipt',
            { body: { image: b64 } }
          );
          if (error) throw error;
          receiptData = data;
        } catch {
          receiptData = await parseReceiptWithOpenAI(b64!);
        }

        if (!receiptData.items || receiptData.items.length === 0) {
          alert.warning(t('scanner.no_items'));
          setEntryMode('landing');
          return;
        }

        if (receiptData.merchant_name) setDescription(receiptData.merchant_name);
        setAmountStr(receiptData.total.toFixed(2));
        if (receiptData.currency) setCurrency(receiptData.currency);
        setScannedItems(receiptData.items);
        setScanExtras({
          tax: receiptData.tax ?? 0,
          serviceCharge: receiptData.service_charge ?? 0,
        });

        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
        await incrementUsage('receipt_scan');
        setEntryMode('form');
      } catch (err: any) {
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
        alert.error(t('common.error'), err.message);
        setEntryMode('landing');
      }
    },
    [canPerform, incrementUsage, navigation, alert, t]
  );

  const removeScannedItem = useCallback(
    (index: number) => {
      setScannedItems((prev) => {
        const updated = prev.filter((_, i) => i !== index);
        const newTotal =
          updated.reduce((s, it) => s + it.total, 0) +
          scanExtras.tax +
          scanExtras.serviceCharge;
        setAmountStr(newTotal.toFixed(2));
        return updated;
      });
    },
    [scanExtras]
  );

  // --- Submit ---
  const handleSplitAndShare = async () => {
    if (!user || !isValid) return;
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    setSaving(true);

    try {
      // Create the quick split record
      const { data: splitData, error: splitError } = await supabase
        .from('quick_splits')
        .insert({
          user_id: user.id,
          description: description.trim(),
          total_amount: totalAmount,
          currency,
        })
        .select()
        .single();

      if (splitError) throw splitError;

      // Create participants
      const participants = people.map((p) => ({
        quick_split_id: splitData.id,
        name: p.name,
        phone: p.phone,
        amount: perPerson,
        is_settled: false,
      }));

      const { error: partError } = await supabase
        .from('quick_split_participants')
        .insert(participants);

      if (partError) throw partError;

      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);

      // Navigate to tracking screen
      navigation.replace('QuickSplitTrack', { quickSplitId: splitData.id });
    } catch (err: any) {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
      alert.error(t('common.error'), err.message || t('common.error'));
    } finally {
      setSaving(false);
    }
  };

  // Landing mode — shown first
  if (entryMode === 'landing') {
    return (
      <View style={[styles.root, { paddingTop: insets.top + Spacing.lg }]}>
        {isDark && (
          <LinearGradient
            colors={colors.headerGradient}
            style={StyleSheet.absoluteFill}
            start={{ x: 0, y: 0 }}
            end={{ x: 0.3, y: 1 }}
          />
        )}
        <StatusBar barStyle={colors.statusBarStyle} />
        <Animated.View style={[styles.landingContent, entrance.style]}>
          {/* Pulsing scan icon */}
          <Animated.View
            style={[styles.iconWrapper, { transform: [{ scale: iconPulse }] }]}
          >
            <LinearGradient
              colors={colors.primaryGradient}
              style={styles.iconCircle}
            >
              <Ionicons name="scan-outline" size={40} color="#FFFFFF" />
            </LinearGradient>
          </Animated.View>

          <Text style={styles.headerTitle}>{t('quick_split.title')}</Text>
          <Text style={styles.heroHint}>{t('quick_split.heroHint')}</Text>

          <View style={styles.scanButtons}>
            <FunButton
              title={t('scanner.take_photo')}
              onPress={() => scanReceipt(true)}
              icon={
                <Ionicons name="camera-outline" size={22} color="#FFFFFF" />
              }
            />
            <FunButton
              title={t('scanner.choose_photo')}
              onPress={() => scanReceipt(false)}
              variant="secondary"
              icon={
                <Ionicons
                  name="images-outline"
                  size={22}
                  color={isDark ? colors.primaryLight : colors.primary}
                />
              }
            />
          </View>

          {/* Divider */}
          <View style={styles.orRow}>
            <View style={styles.orLine} />
            <Text style={styles.orText}>{t('common.or')}</Text>
            <View style={styles.orLine} />
          </View>

          <BouncyPressable
            onPress={() => setEntryMode('form')}
            scaleDown={0.97}
          >
            <View style={styles.manualEntryButton}>
              <Ionicons name="create-outline" size={18} color={colors.primary} />
              <Text style={styles.manualEntryText}>
                {t('quick_split.enterManually')}
              </Text>
            </View>
          </BouncyPressable>
        </Animated.View>
      </View>
    );
  }

  // Scanning mode — fullscreen loading overlay
  if (entryMode === 'scanning') {
    return (
      <View style={styles.loadingContainer}>
        {scanPreviewUri && (
          <Image source={{ uri: scanPreviewUri }} style={styles.previewImage} />
        )}
        <View style={styles.loadingOverlay}>
          <View style={styles.loadingBadge}>
            <ActivityIndicator size="small" color="#14B8A6" />
            <Text style={styles.loadingText}>{t('scanner.scanning')}</Text>
          </View>
        </View>
      </View>
    );
  }

  return (
    <View style={styles.root}>
      <StatusBar barStyle={colors.statusBarStyle} />
      {isDark && (
        <LinearGradient
          colors={colors.headerGradient}
          style={StyleSheet.absoluteFill}
          start={{ x: 0, y: 0 }}
          end={{ x: 0.3, y: 1 }}
        />
      )}

      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        keyboardVerticalOffset={Platform.OS === 'ios' ? 100 : 0}
        style={styles.flex}
      >
        <ScrollView
          contentContainerStyle={[styles.content, { paddingTop: insets.top }]}
          keyboardShouldPersistTaps="handled"
          showsVerticalScrollIndicator={false}
        >
          <Animated.View style={entrance.style}>
            {/* Header */}
            <View style={styles.headerBlock}>
              <Text style={styles.headerKicker}>
                {t('quick_split.kicker')}
              </Text>
              <Text style={styles.headerTitle}>
                {t('quick_split.title')}
              </Text>
            </View>

            {/* Bill Details Card */}
            <ThemedCard accent style={styles.card}>
              <ThemedInput
                label={t('quick_split.whatFor')}
                value={description}
                onChangeText={setDescription}
                placeholder={t('quick_split.whatForPlaceholder')}
                maxLength={80}
                autoFocus
                containerStyle={styles.field}
              />

              <ThemedInput
                label={t('quick_split.totalAmount')}
                value={amountStr}
                onChangeText={setAmountStr}
                placeholder="0.00"
                keyboardType="decimal-pad"
                containerStyle={styles.field}
              />

              {/* Currency pills */}
              <View style={styles.fieldLast}>
                <Text style={styles.label}>{t('groups.currency')}</Text>
                <ScrollView
                  horizontal
                  showsHorizontalScrollIndicator={false}
                  contentContainerStyle={styles.currencyRow}
                >
                  {CURRENCIES.map((cur) => {
                    const isActive = currency === cur;
                    return (
                      <BouncyPressable
                        key={cur}
                        onPress={() => {
                          Haptics.selectionAsync();
                          setCurrency(cur);
                        }}
                        scaleDown={0.95}
                      >
                        <View
                          style={[
                            styles.currencyPill,
                            isActive && styles.currencyPillActive,
                          ]}
                        >
                          <Text
                            style={[
                              styles.currencyText,
                              isActive && styles.currencyTextActive,
                            ]}
                          >
                            {cur}
                          </Text>
                        </View>
                      </BouncyPressable>
                    );
                  })}
                </ScrollView>
              </View>
            </ThemedCard>

            {/* Scanned items section — shown only when receipt was scanned */}
            {scannedItems.length > 0 && (
              <View>
                <View style={styles.sectionHeader}>
                  <Text style={styles.sectionTitle}>
                    {t('quick_split.scannedItems')}
                  </Text>
                  <BouncyPressable
                    onPress={() => {
                      setScannedItems([]);
                      setScanExtras({ tax: 0, serviceCharge: 0 });
                    }}
                    scaleDown={0.97}
                  >
                    <Text style={styles.clearItemsText}>{t('common.clear')}</Text>
                  </BouncyPressable>
                </View>
                <ThemedCard style={styles.card}>
                  {scannedItems.map((item, index) => (
                    <View key={index} style={styles.scannedItemRow}>
                      <View style={styles.scannedItemInfo}>
                        <Text style={styles.scannedItemName} numberOfLines={1}>
                          {item.name}
                        </Text>
                        <Text style={styles.scannedItemMeta}>
                          ×{item.quantity} @ {item.unit_price.toFixed(2)}
                        </Text>
                      </View>
                      <Text style={styles.scannedItemPrice}>
                        {item.total.toFixed(2)}
                      </Text>
                      <BouncyPressable
                        onPress={() => removeScannedItem(index)}
                        scaleDown={0.9}
                      >
                        <Ionicons
                          name="close-circle-outline"
                          size={20}
                          color={colors.textTertiary}
                        />
                      </BouncyPressable>
                    </View>
                  ))}
                  {scanExtras.tax > 0 && (
                    <View style={styles.scannedExtraRow}>
                      <Text style={styles.scannedExtraLabel}>
                        {t('scanner.tax')}
                      </Text>
                      <Text style={styles.scannedExtraValue}>
                        +{scanExtras.tax.toFixed(2)}
                      </Text>
                    </View>
                  )}
                  {scanExtras.serviceCharge > 0 && (
                    <View style={styles.scannedExtraRow}>
                      <Text style={styles.scannedExtraLabel}>
                        {t('scanner.service_charge')}
                      </Text>
                      <Text style={styles.scannedExtraValue}>
                        +{scanExtras.serviceCharge.toFixed(2)}
                      </Text>
                    </View>
                  )}
                </ThemedCard>
              </View>
            )}

            {/* Back to scan link */}
            {scannedItems.length > 0 && (
              <BouncyPressable
                onPress={() => {
                  setEntryMode('landing');
                  setScannedItems([]);
                  setScanExtras({ tax: 0, serviceCharge: 0 });
                  setScanPreviewUri(null);
                }}
                scaleDown={0.97}
              >
                <View style={styles.backToScanRow}>
                  <Ionicons
                    name="scan-outline"
                    size={14}
                    color={colors.primary}
                  />
                  <Text style={styles.backToScanText}>
                    {t('quick_split.scanAgain')}
                  </Text>
                </View>
              </BouncyPressable>
            )}

            {/* People Section */}
            <View style={styles.sectionHeader}>
              <Text style={styles.sectionTitle}>
                {t('quick_split.people')}
              </Text>
              {people.length > 0 && (
                <Text style={styles.sectionCount}>
                  {people.length + 1} {t('quick_split.splitting')}
                </Text>
              )}
            </View>

            {/* Payer (you) */}
            <ThemedCard style={styles.personCard}>
              <View style={styles.personRow}>
                <LinearGradient
                  colors={colors.primaryGradient}
                  start={{ x: 0, y: 0 }}
                  end={{ x: 1, y: 1 }}
                  style={styles.avatar}
                >
                  <Ionicons name="person" size={16} color="#FFFFFF" />
                </LinearGradient>
                <View style={styles.personInfo}>
                  <Text style={styles.personName}>
                    {profile?.display_name || t('common.you')}{' '}
                    <Text style={styles.youBadge}>({t('common.you')})</Text>
                  </Text>
                  <Text style={styles.personRole}>
                    {t('quick_split.payer')}
                  </Text>
                </View>
                {perPerson > 0 && (
                  <Text style={styles.personAmount}>
                    {formatCurrency(perPerson, currency)}
                  </Text>
                )}
              </View>
            </ThemedCard>

            {/* Added people */}
            {people.map((person) => {
              const grad = avatarGradient(person.name);
              return (
                <ThemedCard key={person.id} style={styles.personCard}>
                  <View style={styles.personRow}>
                    <LinearGradient
                      colors={grad}
                      start={{ x: 0, y: 0 }}
                      end={{ x: 1, y: 1 }}
                      style={styles.avatar}
                    >
                      <Text style={styles.avatarText}>
                        {getInitials(person.name)}
                      </Text>
                    </LinearGradient>
                    <View style={styles.personInfo}>
                      <Text style={styles.personName}>{person.name}</Text>
                      {person.phone && (
                        <Text style={styles.personPhone}>{person.phone}</Text>
                      )}
                    </View>
                    {perPerson > 0 && (
                      <Text style={styles.personAmount}>
                        {formatCurrency(perPerson, currency)}
                      </Text>
                    )}
                    <BouncyPressable
                      onPress={() => removePerson(person.id)}
                      scaleDown={0.9}
                    >
                      <View style={styles.removeBtn}>
                        <Ionicons
                          name="close"
                          size={16}
                          color={colors.textTertiary}
                        />
                      </View>
                    </BouncyPressable>
                  </View>
                </ThemedCard>
              );
            })}

            {/* Add person buttons */}
            <View style={styles.addRow}>
              <BouncyPressable onPress={openContactsPicker} scaleDown={0.95}>
                <View style={styles.addButton}>
                  <Ionicons
                    name="people-outline"
                    size={18}
                    color={colors.primary}
                  />
                  <Text style={styles.addButtonText}>
                    {t('quick_split.fromContacts')}
                  </Text>
                </View>
              </BouncyPressable>

              <BouncyPressable
                onPress={() => {
                  Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
                  setManualName('');
                  setManualPhone('');
                  setAddModalVisible(true);
                }}
                scaleDown={0.95}
              >
                <View style={styles.addButton}>
                  <Ionicons
                    name="person-add-outline"
                    size={18}
                    color={colors.primary}
                  />
                  <Text style={styles.addButtonText}>
                    {t('quick_split.addManually')}
                  </Text>
                </View>
              </BouncyPressable>

              <BouncyPressable onPress={openNearbyModal} scaleDown={0.95}>
                <View style={[styles.addButton, styles.addButtonNearby]}>
                  <Ionicons
                    name="bluetooth-outline"
                    size={18}
                    color={colors.primary}
                  />
                  <Text style={styles.addButtonText}>
                    {t('quick_split.findNearby')}
                  </Text>
                </View>
              </BouncyPressable>
            </View>

            {/* Split preview */}
            {isValid && (
              <ThemedCard accent style={styles.previewCard}>
                <View style={styles.previewRow}>
                  <View>
                    <Text style={styles.previewLabel}>
                      {t('quick_split.perPerson')}
                    </Text>
                    <Text style={styles.previewAmount}>
                      {formatCurrency(perPerson, currency)}
                    </Text>
                  </View>
                  <View style={styles.previewDivider} />
                  <View style={{ alignItems: 'flex-end' }}>
                    <Text style={styles.previewLabel}>
                      {t('quick_split.totalLabel')}
                    </Text>
                    <Text style={styles.previewTotal}>
                      {formatCurrency(totalAmount, currency)}
                    </Text>
                  </View>
                </View>
                <View style={styles.previewSplitLine}>
                  <Ionicons
                    name="git-branch-outline"
                    size={14}
                    color={colors.textTertiary}
                  />
                  <Text style={styles.previewSplitText}>
                    {t('quick_split.splitAmong', { count: splitCount })}
                  </Text>
                </View>
              </ThemedCard>
            )}

            {/* Action button */}
            <FunButton
              title={t('quick_split.splitAndShare')}
              onPress={handleSplitAndShare}
              loading={saving}
              disabled={!isValid}
              icon={
                <Ionicons
                  name="paper-plane-outline"
                  size={20}
                  color="#FFFFFF"
                />
              }
            />

            <View style={{ height: 80 }} />
          </Animated.View>
        </ScrollView>
      </KeyboardAvoidingView>

      {/* --- Manual Add Person Modal --- */}
      <Modal
        visible={addModalVisible}
        transparent
        animationType="slide"
        onRequestClose={() => setAddModalVisible(false)}
      >
        <Pressable
          style={styles.modalOverlay}
          onPress={() => setAddModalVisible(false)}
        >
          <KeyboardAvoidingView
            behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
          >
            <Pressable style={styles.modalContent} onPress={() => {}}>
              <View style={styles.modalHandle} />
              <Text style={styles.modalTitle}>
                {t('quick_split.addPerson')}
              </Text>

              <ThemedInput
                label={t('quick_split.personName')}
                value={manualName}
                onChangeText={setManualName}
                placeholder={t('quick_split.personNamePlaceholder')}
                autoFocus
                containerStyle={styles.field}
              />

              <ThemedInput
                label={t('quick_split.personPhone')}
                value={manualPhone}
                onChangeText={setManualPhone}
                placeholder={t('quick_split.personPhonePlaceholder')}
                keyboardType="phone-pad"
                containerStyle={styles.field}
              />

              <FunButton
                title={t('quick_split.addPerson')}
                onPress={addManualPerson}
                disabled={!manualName.trim()}
                icon={
                  <Ionicons
                    name="person-add-outline"
                    size={20}
                    color="#FFFFFF"
                  />
                }
              />
            </Pressable>
          </KeyboardAvoidingView>
        </Pressable>
      </Modal>

      {/* --- Contacts Picker Modal --- */}
      <Modal
        visible={contactsModalVisible}
        transparent
        animationType="slide"
        onRequestClose={() => setContactsModalVisible(false)}
      >
        <Pressable
          style={styles.modalOverlay}
          onPress={() => setContactsModalVisible(false)}
        >
          <Pressable
            style={[styles.modalContent, styles.contactsModal]}
            onPress={() => {}}
          >
            <View style={styles.modalHandle} />
            <Text style={styles.modalTitle}>
              {t('quick_split.pickContact')}
            </Text>

            <ThemedInput
              value={contactSearch}
              onChangeText={setContactSearch}
              placeholder={t('addFriends.searchPlaceholder')}
              icon="search-outline"
              containerStyle={styles.contactSearchField}
            />

            {loadingContacts ? (
              <View style={styles.contactsLoading}>
                <ActivityIndicator size="large" color={colors.primary} />
              </View>
            ) : (
              <FlatList
                data={filteredContacts}
                keyExtractor={(item) => item.id}
                renderItem={({ item }) => {
                  const alreadyAdded = people.some(
                    (p) => p.phone === item.phone
                  );
                  const grad = avatarGradient(item.name);
                  return (
                    <BouncyPressable
                      onPress={() => !alreadyAdded && addContactAsPerson(item)}
                      scaleDown={0.97}
                    >
                      <View
                        style={[
                          styles.contactRow,
                          alreadyAdded && styles.contactRowDisabled,
                        ]}
                      >
                        <LinearGradient
                          colors={grad}
                          start={{ x: 0, y: 0 }}
                          end={{ x: 1, y: 1 }}
                          style={styles.contactAvatar}
                        >
                          <Text style={styles.contactAvatarText}>
                            {getInitials(item.name)}
                          </Text>
                        </LinearGradient>
                        <View style={styles.contactInfo}>
                          <Text style={styles.contactName}>{item.name}</Text>
                          <Text style={styles.contactPhone}>{item.phone}</Text>
                        </View>
                        {alreadyAdded && (
                          <Ionicons
                            name="checkmark-circle"
                            size={20}
                            color={colors.success}
                          />
                        )}
                      </View>
                    </BouncyPressable>
                  );
                }}
                style={styles.contactsList}
                showsVerticalScrollIndicator={false}
                ListEmptyComponent={
                  <Text style={styles.emptyContactsText}>
                    {t('addFriends.noContacts')}
                  </Text>
                }
              />
            )}
          </Pressable>
        </Pressable>
      </Modal>

      {/* --- BLE Nearby Users Modal --- */}
      <Modal
        visible={nearbyModalVisible}
        transparent
        animationType="slide"
        onRequestClose={closeNearbyModal}
      >
        <Pressable style={styles.modalOverlay} onPress={closeNearbyModal}>
          <Pressable
            style={[styles.modalContent, styles.nearbyModal]}
            onPress={() => {}}
          >
            <View style={styles.modalHandle} />

            {/* Header row with scanning indicator */}
            <View style={styles.nearbyHeader}>
              <Text style={styles.modalTitle}>
                {t('quick_split.nearbyTitle')}
              </Text>
              {isScanning && (
                <View style={styles.scanningBadge}>
                  <ActivityIndicator size="small" color={colors.primary} />
                  <Text style={styles.scanningText}>
                    {t('quick_split.scanning')}
                  </Text>
                </View>
              )}
            </View>

            <Text style={styles.nearbySubtitle}>
              {t('quick_split.nearbySubtitle')}
            </Text>

            {/* BLE error state */}
            {bleError && (
              <View style={styles.nearbyError}>
                <Ionicons
                  name="warning-outline"
                  size={20}
                  color={colors.danger}
                />
                <Text style={styles.nearbyErrorText}>
                  {bleError === 'bluetooth_permission_denied'
                    ? t('quick_split.bluetoothPermissionDenied')
                    : t('quick_split.bluetoothError')}
                </Text>
              </View>
            )}

            {/* Empty state while scanning */}
            {!bleError && nearbyUsers.length === 0 && isScanning && (
              <View style={styles.nearbyEmpty}>
                <Ionicons
                  name="radio-outline"
                  size={48}
                  color={colors.textTertiary}
                />
                <Text style={styles.nearbyEmptyText}>
                  {t('quick_split.lookingAround')}
                </Text>
              </View>
            )}

            {/* No results after scan finished */}
            {!bleError && nearbyUsers.length === 0 && !isScanning && (
              <View style={styles.nearbyEmpty}>
                <Ionicons
                  name="people-outline"
                  size={48}
                  color={colors.textTertiary}
                />
                <Text style={styles.nearbyEmptyText}>
                  {t('quick_split.noNearbyFound')}
                </Text>
              </View>
            )}

            {/* Discovered users list */}
            <FlatList
              data={nearbyUsers}
              keyExtractor={(item) => item.id}
              renderItem={({ item }) => {
                const alreadyAdded = people.some((p) => p.id === item.id);
                const grad = avatarGradient(item.display_name);
                return (
                  <BouncyPressable
                    onPress={() =>
                      !alreadyAdded && addNearbyUserAsPerson(item)
                    }
                    scaleDown={0.97}
                  >
                    <View
                      style={[
                        styles.contactRow,
                        alreadyAdded && styles.contactRowDisabled,
                      ]}
                    >
                      <LinearGradient
                        colors={grad}
                        start={{ x: 0, y: 0 }}
                        end={{ x: 1, y: 1 }}
                        style={styles.contactAvatar}
                      >
                        <Text style={styles.contactAvatarText}>
                          {getInitials(item.display_name)}
                        </Text>
                      </LinearGradient>
                      <View style={styles.contactInfo}>
                        <Text style={styles.contactName}>
                          {item.display_name}
                        </Text>
                        {item.phone && (
                          <Text style={styles.contactPhone}>
                            {item.phone}
                          </Text>
                        )}
                      </View>
                      {alreadyAdded ? (
                        <Ionicons
                          name="checkmark-circle"
                          size={20}
                          color={colors.success}
                        />
                      ) : (
                        <View style={styles.addChip}>
                          <Text style={styles.addChipText}>
                            {t('common.add')}
                          </Text>
                        </View>
                      )}
                    </View>
                  </BouncyPressable>
                );
              }}
              style={styles.contactsList}
              showsVerticalScrollIndicator={false}
            />
          </Pressable>
        </Pressable>
      </Modal>
    </View>
  );
}

const createStyles = (c: ThemeColors, isDark: boolean) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: c.bg },
    flex: { flex: 1 },
    content: {
      padding: Spacing.xl,
      paddingTop: Spacing.md,
      paddingBottom: 60,
    },

    /* Header */
    headerBlock: { marginBottom: Spacing.xxl },
    headerKicker: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 10,
      letterSpacing: 4,
      color: c.kicker,
      marginBottom: Spacing.xs,
    },
    headerTitle: {
      fontFamily: FontFamily.display,
      fontSize: 32,
      letterSpacing: -1,
      color: c.text,
      marginBottom: Spacing.sm,
    },
    heroHint: {
      fontFamily: FontFamily.body,
      fontSize: 15,
      color: c.textSecondary,
      textAlign: 'center',
      marginBottom: Spacing.xxl,
    },

    /* Card */
    card: { marginBottom: Spacing.xl },
    field: { marginBottom: Spacing.xl },
    fieldLast: { marginBottom: 0 },
    label: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 11,
      letterSpacing: 1.5,
      color: isDark ? c.kicker : c.textSecondary,
      textTransform: 'uppercase',
      marginBottom: Spacing.sm,
    },

    /* Currency pills */
    currencyRow: { flexDirection: 'row', gap: Spacing.sm },
    currencyPill: {
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: Radius.full,
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : c.borderLight,
    },
    currencyPillActive: {
      backgroundColor: c.primary,
    },
    currencyText: {
      fontSize: 13,
      fontFamily: FontFamily.bodySemibold,
      color: c.textTertiary,
    },
    currencyTextActive: {
      color: '#FFFFFF',
    },

    /* Section */
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.md,
    },
    sectionTitle: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 11,
      letterSpacing: 3,
      color: isDark ? c.kicker : c.textSecondary,
      textTransform: 'uppercase',
    },
    sectionCount: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 11,
      letterSpacing: 1,
      color: c.primary,
    },

    /* Person card */
    personCard: { marginBottom: Spacing.sm },
    personRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: Radius.full,
      justifyContent: 'center',
      alignItems: 'center',
    },
    avatarText: {
      fontFamily: FontFamily.bodyBold,
      fontSize: 14,
      color: '#FFFFFF',
    },
    personInfo: { flex: 1 },
    personName: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 15,
      color: c.text,
    },
    youBadge: {
      fontFamily: FontFamily.body,
      fontSize: 12,
      color: c.textTertiary,
    },
    personRole: {
      fontFamily: FontFamily.body,
      fontSize: 12,
      color: c.primary,
      marginTop: 1,
    },
    personPhone: {
      fontFamily: FontFamily.body,
      fontSize: 12,
      color: c.textTertiary,
      marginTop: 1,
    },
    personAmount: {
      fontFamily: FontFamily.bodyBold,
      fontSize: 16,
      color: c.primary,
      letterSpacing: -0.3,
    },
    removeBtn: {
      width: 28,
      height: 28,
      borderRadius: Radius.full,
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : c.borderLight,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: Spacing.xs,
    },

    /* Add buttons */
    addRow: {
      flexDirection: 'row',
      gap: Spacing.sm,
      marginTop: Spacing.sm,
      marginBottom: Spacing.xl,
    },
    addButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      borderRadius: Radius.full,
      borderWidth: 1.5,
      borderColor: c.primary,
      borderStyle: 'dashed',
    },
    addButtonText: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 13,
      color: c.primary,
    },

    /* Preview */
    previewCard: { marginBottom: Spacing.xl },
    previewRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    previewLabel: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 10,
      letterSpacing: 2,
      color: c.textTertiary,
      textTransform: 'uppercase',
      marginBottom: 4,
    },
    previewAmount: {
      fontFamily: FontFamily.display,
      fontSize: 28,
      color: c.primary,
      letterSpacing: -1,
    },
    previewTotal: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 18,
      color: c.text,
      letterSpacing: -0.3,
    },
    previewDivider: {
      width: 1,
      height: 40,
      backgroundColor: c.borderLight,
    },
    previewSplitLine: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: Spacing.md,
      paddingTop: Spacing.md,
      borderTopWidth: 1,
      borderTopColor: c.borderLight,
    },
    previewSplitText: {
      fontFamily: FontFamily.body,
      fontSize: 13,
      color: c.textTertiary,
    },

    /* Modal */
    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: c.overlay,
    },
    modalContent: {
      backgroundColor: c.bgCard,
      borderTopLeftRadius: Radius.xxl,
      borderTopRightRadius: Radius.xxl,
      padding: Spacing.xl,
      paddingBottom: Spacing.huge,
    },
    modalHandle: {
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: c.borderLight,
      alignSelf: 'center',
      marginBottom: Spacing.lg,
    },
    modalTitle: {
      fontFamily: FontFamily.display,
      fontSize: 20,
      color: c.text,
      marginBottom: Spacing.lg,
      letterSpacing: -0.3,
    },

    /* Contacts modal */
    contactsModal: {
      maxHeight: '80%',
    },
    contactSearchField: { marginBottom: Spacing.md },
    contactsLoading: {
      paddingVertical: Spacing.huge,
      alignItems: 'center',
    },
    contactsList: {
      maxHeight: 400,
    },
    contactRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.md,
      gap: Spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: c.borderLight,
    },
    contactRowDisabled: {
      opacity: 0.5,
    },
    contactAvatar: {
      width: 36,
      height: 36,
      borderRadius: Radius.full,
      justifyContent: 'center',
      alignItems: 'center',
    },
    contactAvatarText: {
      fontFamily: FontFamily.bodyBold,
      fontSize: 12,
      color: '#FFFFFF',
    },
    contactInfo: { flex: 1 },
    contactName: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 15,
      color: c.text,
    },
    contactPhone: {
      fontFamily: FontFamily.body,
      fontSize: 12,
      color: c.textTertiary,
    },
    emptyContactsText: {
      fontFamily: FontFamily.body,
      fontSize: 14,
      color: c.textTertiary,
      textAlign: 'center',
      paddingVertical: Spacing.xxxl,
    },

    /* Add button variants */
    addButtonNearby: {
      borderColor: c.accent,
    },

    /* Nearby modal */
    nearbyModal: {
      maxHeight: '75%',
    },
    nearbyHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: Spacing.sm,
    },
    scanningBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: c.primarySurface,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: Radius.full,
    },
    scanningText: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 11,
      color: c.primary,
    },
    nearbySubtitle: {
      fontFamily: FontFamily.body,
      fontSize: 13,
      color: c.textTertiary,
      marginBottom: Spacing.lg,
    },
    nearbyEmpty: {
      alignItems: 'center',
      paddingVertical: Spacing.xxxl,
      gap: Spacing.md,
    },
    nearbyEmptyText: {
      fontFamily: FontFamily.body,
      fontSize: 14,
      color: c.textTertiary,
      textAlign: 'center',
    },
    nearbyError: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      backgroundColor: c.dangerLight + '20',
      padding: Spacing.md,
      borderRadius: Radius.md,
      marginBottom: Spacing.md,
    },
    nearbyErrorText: {
      fontFamily: FontFamily.body,
      fontSize: 13,
      color: c.danger,
      flex: 1,
    },
    addChip: {
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: Radius.full,
      backgroundColor: c.primarySurface,
    },
    addChipText: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 12,
      color: c.primary,
    },

    /* Landing screen */
    landingContent: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.xxl,
    },
    iconWrapper: {
      width: 120,
      height: 120,
      marginBottom: Spacing.xxl,
      justifyContent: 'center',
      alignItems: 'center',
    },
    iconCircle: {
      width: 88,
      height: 88,
      borderRadius: 28,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.4,
      shadowRadius: 20,
      elevation: 12,
    },
    scanButtons: { width: '100%', gap: Spacing.md, marginBottom: Spacing.xxl },
    orRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
      marginVertical: Spacing.xxl,
      width: '100%',
    },
    orLine: { flex: 1, height: 1, backgroundColor: c.borderLight },
    orText: {
      fontFamily: FontFamily.body,
      fontSize: 13,
      color: c.textTertiary,
    },
    manualEntryButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.xl,
      borderRadius: Radius.full,
      borderWidth: 1,
      borderColor: c.borderLight,
    },
    manualEntryText: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 14,
      color: c.primary,
    },

    /* Scanning overlay */
    loadingContainer: {
      flex: 1,
      backgroundColor: isDark ? '#040D0B' : '#0A1210',
    },
    previewImage: { flex: 1, resizeMode: 'contain' },
    loadingOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(10,18,16,0.75)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: 'rgba(0,0,0,0.5)',
      paddingHorizontal: 24,
      paddingVertical: 14,
      borderRadius: Radius.full,
    },
    loadingText: {
      color: '#F4F0E8',
      fontFamily: FontFamily.bodySemibold,
      fontSize: 16,
    },

    /* Scanned items */
    scannedItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.sm,
      gap: Spacing.sm,
      borderBottomWidth: 1,
      borderBottomColor: c.borderLight,
    },
    scannedItemInfo: { flex: 1 },
    scannedItemName: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 14,
      color: c.text,
    },
    scannedItemMeta: {
      fontFamily: FontFamily.body,
      fontSize: 11,
      color: c.textTertiary,
      marginTop: 2,
    },
    scannedItemPrice: {
      fontFamily: FontFamily.bodyBold,
      fontSize: 14,
      color: c.text,
    },
    scannedExtraRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 5,
      opacity: 0.7,
    },
    scannedExtraLabel: {
      fontFamily: FontFamily.body,
      fontSize: 12,
      color: c.textTertiary,
    },
    scannedExtraValue: {
      fontFamily: FontFamily.bodySemibold,
      fontSize: 12,
      color: c.textSecondary,
    },
    clearItemsText: {
      fontFamily: FontFamily.body,
      fontSize: 12,
      color: c.textTertiary,
    },
    backToScanRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      marginBottom: Spacing.sm,
    },
    backToScanText: {
      fontFamily: FontFamily.body,
      fontSize: 12,
      color: c.primary,
    },
  });
